using System;
using System.Collections.Generic;
using System.Text;

namespace MemoryRandomizer.Core
{
    internal class Abilities
    {
        public static List<RandomizableItem> AbilityList = new List<RandomizableItem>()
        {
            // Gunner
            new RandomizableItem("Potshot", 1, true, RandoItemType.Ability, 0x6, 20),
            new RandomizableItem("Cheap Shot", 1, true, RandoItemType.Ability, 0x8, 30),
            new RandomizableItem("Enchanted Ammo", 1, true, RandoItemType.Ability, 0xA, 30),
            new RandomizableItem("Target MP", 1, true, RandoItemType.Ability, 0xC, 30),
            new RandomizableItem("Quarter Pounder", 1, true, RandoItemType.Ability, 0xE, 40),
            new RandomizableItem("On the Level", 1, true, RandoItemType.Ability, 0x10, 40),
            new RandomizableItem("Burst Shot", 1, true, RandoItemType.Ability, 0x12, 60),
            new RandomizableItem("Tableturner", 1, true, RandoItemType.Ability, 0x14, 60),
            new RandomizableItem("Scattershot", 1, true, RandoItemType.Ability, 0x16, 80),
            new RandomizableItem("Scatterburst", 1, true, RandoItemType.Ability, 0x18, 120),
            new RandomizableItem("Darkproof", 1, true, RandoItemType.Ability, 0x4E4, 30),
            new RandomizableItem("Sleepproof", 1, true, RandoItemType.Ability, 0x4DC, 30),
            new RandomizableItem("Trigger Happy Lv2", 1, true, RandoItemType.Ability, 0x470, 80),
            new RandomizableItem("Trigger Happy Lv3", 1, true, RandoItemType.Ability, 0x472, 150),

            // Gun Mage
            new RandomizableItem("Shell Cracker", 2, true, RandoItemType.Ability, 0x1C, 20),
            new RandomizableItem("Anti Aircraft", 2, true, RandoItemType.Ability, 0x1E, 20),
            new RandomizableItem("Silver Bullet", 2, true, RandoItemType.Ability, 0x20, 20),
            new RandomizableItem("Flan Eater", 2, true, RandoItemType.Ability, 0x22, 20),
            new RandomizableItem("Elementillery", 2, true, RandoItemType.Ability, 0x24, 20),
            new RandomizableItem("Killasaurus", 2, true, RandoItemType.Ability, 0x26, 20),
            new RandomizableItem("Drake Slayer", 2, true, RandoItemType.Ability, 0x28, 20),
            new RandomizableItem("Dismantler", 2, true, RandoItemType.Ability, 0x2A, 20),
            new RandomizableItem("Mech Destroyer", 2, true, RandoItemType.Ability, 0x2C, 20),
            new RandomizableItem("Demon Muzzle", 2, true, RandoItemType.Ability, 0x2E, 20),
            new RandomizableItem("Fiend Hunter", 2, true, RandoItemType.Ability, 0x47C, 30),
            new RandomizableItem("Scan Lv2", 2, true, RandoItemType.Ability, 0x474, 20),
            new RandomizableItem("Scan Lv3", 2, true, RandoItemType.Ability, 0x476, 100),

            // Alchemist
            new RandomizableItem("Potion", 3, true, RandoItemType.Ability, 0x52, 10),
            new RandomizableItem("Hi-Potion", 3, true, RandoItemType.Ability, 0x54, 40),
            new RandomizableItem("Mega Potion", 3, true, RandoItemType.Ability, 0x56, 120),
            new RandomizableItem("X-Potion", 3, true, RandoItemType.Ability, 0x58, 160),
            new RandomizableItem("Remedy", 3, true, RandoItemType.Ability, 0x5A, 20),
            new RandomizableItem("Dispel Tonic", 3, true, RandoItemType.Ability, 0x5C, 20),
            new RandomizableItem("Phoenix Down", 3, true, RandoItemType.Ability, 0x5E, 30),
            new RandomizableItem("Mega Phoenix", 3, true, RandoItemType.Ability, 0x60, 200),
            new RandomizableItem("Ether", 3, true, RandoItemType.Ability, 0x62, 400),
            new RandomizableItem("Elixir", 3, true, RandoItemType.Ability, 0x64, 999),
            new RandomizableItem("Items Lv2", 3, true, RandoItemType.Ability, 0x47E, 30),
            new RandomizableItem("Chemist", 3, true, RandoItemType.Ability, 0x44C, 40),
            new RandomizableItem("Elementalist", 3, true, RandoItemType.Ability, 0x44E, 80),
            new RandomizableItem("Physicist", 3, true, RandoItemType.Ability, 0x450, 100),

            // Warrior
            new RandomizableItem("Sentinel", 4, true, RandoItemType.Ability, 0x68, 20),
            new RandomizableItem("Flametongue", 4, true, RandoItemType.Ability, 0x72, 20),
            new RandomizableItem("Ice Brand", 4, true, RandoItemType.Ability, 0x74, 20),
            new RandomizableItem("Thunder Blade", 4, true, RandoItemType.Ability, 0x76, 20),
            new RandomizableItem("Liquid Steel", 4, true, RandoItemType.Ability, 0x78, 20),
            new RandomizableItem("Demi Sword", 4, true, RandoItemType.Ability, 0x7A, 60),
            new RandomizableItem("Excalibur", 4, true, RandoItemType.Ability, 0x7C, 120),
            new RandomizableItem("Armor Break", 4, true, RandoItemType.Ability, 0x6C, 30),
            new RandomizableItem("Magic Break", 4, true, RandoItemType.Ability, 0x6E, 30),
            new RandomizableItem("Mental Break", 4, true, RandoItemType.Ability, 0x70, 30),
            new RandomizableItem("Delay Attack", 4, true, RandoItemType.Ability, 0x7E, 100),
            new RandomizableItem("Delay Buster", 4, true, RandoItemType.Ability, 0x80, 120),
            new RandomizableItem("Assault", 4, true, RandoItemType.Ability, 0x66, 100),
            new RandomizableItem("SOS Protect", 4, true, RandoItemType.Ability, 0x52A, 20),

            // Samurai
            new RandomizableItem("Spare Change", 5, true, RandoItemType.Ability, 0x9A, 20),
            new RandomizableItem("Magicide", 5, true, RandoItemType.Ability, 0x84, 30),
            new RandomizableItem("Dismissal", 5, true, RandoItemType.Ability, 0x86, 30),
            new RandomizableItem("Fingersnap", 5, true, RandoItemType.Ability, 0x88, 40),
            new RandomizableItem("Sparkler", 5, true, RandoItemType.Ability, 0x8A, 40),
            new RandomizableItem("Fireworks", 5, true, RandoItemType.Ability, 0x8C, 60),
            new RandomizableItem("Momentum", 5, true, RandoItemType.Ability, 0x8E, 60),
            new RandomizableItem("Shin-Zantetsu", 5, true, RandoItemType.Ability, 0x90, 100),
            new RandomizableItem("Nonpareil", 5, true, RandoItemType.Ability, 0x92, 20),
            new RandomizableItem("No Fear", 5, true, RandoItemType.Ability, 0x94, 30),
            new RandomizableItem("Clean Slate", 5, true, RandoItemType.Ability, 0x96, 40),
            new RandomizableItem("Hayate", 5, true, RandoItemType.Ability, 0x98, 60),
            new RandomizableItem("Zantetsu", 5, true, RandoItemType.Ability, 0x9C, 140),
            new RandomizableItem("SOS Critical", 5, true, RandoItemType.Ability, 0x536, 80),

            // Dark Knight
            new RandomizableItem("Drain", 6, true, RandoItemType.Ability, 0xA2, 30),
            new RandomizableItem("Demi", 6, true, RandoItemType.Ability, 0xA4, 30),
            new RandomizableItem("Confuse", 6, true, RandoItemType.Ability, 0xA6, 30),
            new RandomizableItem("Break", 6, true, RandoItemType.Ability, 0xA8, 40),
            new RandomizableItem("Bio", 6, true, RandoItemType.Ability, 0xAA, 40),
            new RandomizableItem("Doom", 6, true, RandoItemType.Ability, 0xAC, 20),
            new RandomizableItem("Death", 6, true, RandoItemType.Ability, 0xAE, 60),
            new RandomizableItem("Black Sky", 6, true, RandoItemType.Ability, 0xB0, 100),
            new RandomizableItem("Charon", 6, true, RandoItemType.Ability, 0xA0, 100),
            new RandomizableItem("Poisonproof", 6, true, RandoItemType.Ability, 0x4E8, 30),
            new RandomizableItem("Stoneproof", 6, true, RandoItemType.Ability, 0x4D8, 30),
            new RandomizableItem("Confuseproof", 6, true, RandoItemType.Ability, 0x4EC, 40),
            new RandomizableItem("Curseproof", 6, true, RandoItemType.Ability, 0x4F6, 60),
            new RandomizableItem("Deathproof", 6, true, RandoItemType.Ability, 0x4D4, 140),

            // Berserker
            new RandomizableItem("Cripple", 7, true, RandoItemType.Ability, 0xB6, 20),
            new RandomizableItem("Mad Rush", 7, true, RandoItemType.Ability, 0xB8, 30),
            new RandomizableItem("Crackdown", 7, true, RandoItemType.Ability, 0xBA, 30),
            new RandomizableItem("Eject", 7, true, RandoItemType.Ability, 0xBC, 40),
            new RandomizableItem("Unhinge", 7, true, RandoItemType.Ability, 0xBE, 40),
            new RandomizableItem("Intimidate", 7, true, RandoItemType.Ability, 0xC0, 50),
            new RandomizableItem("Envenom", 7, true, RandoItemType.Ability, 0xC2, 30),
            new RandomizableItem("Hurt", 7, true, RandoItemType.Ability, 0xC4, 60),
            new RandomizableItem("Howl", 7, true, RandoItemType.Ability, 0xB4, 80),
            new RandomizableItem("Itchproof", 7, true, RandoItemType.Ability, 0x4FA, 20),
            new RandomizableItem("Counterattack", 7, true, RandoItemType.Ability, 0x444, 180),
            new RandomizableItem("Magic Counter", 7, true, RandoItemType.Ability, 0x448, 300),
            new RandomizableItem("Evade & Counter", 7, true, RandoItemType.Ability, 0x446, 400),
            new RandomizableItem("Auto-Regen", 7, true, RandoItemType.Ability, 0x51C, 80),

            // Songstress
            new RandomizableItem("Samba of Silence", 8, true, RandoItemType.Ability, 0xC8, 20),
            new RandomizableItem("MP Mambo", 8, true, RandoItemType.Ability, 0xCA, 20),
            new RandomizableItem("Magical Masque", 8, true, RandoItemType.Ability, 0xCC, 20),
            new RandomizableItem("Sleepy Shuffle", 8, true, RandoItemType.Ability, 0xCE, 80),
            new RandomizableItem("Carnival Cancan", 8, true, RandoItemType.Ability, 0xD0, 80),
            new RandomizableItem("Slow Dance", 8, true, RandoItemType.Ability, 0xD2, 60),
            new RandomizableItem("Breakdance", 8, true, RandoItemType.Ability, 0xD4, 120),
            new RandomizableItem("Jitterbug", 8, true, RandoItemType.Ability, 0xD6, 120),
            new RandomizableItem("Dirty Dancing", 8, true, RandoItemType.Ability, 0xD8, 160),
            new RandomizableItem("Battle Cry", 8, true, RandoItemType.Ability, 0xDA, 10),
            new RandomizableItem("Cantus Firmus", 8, true, RandoItemType.Ability, 0xDC, 10),
            new RandomizableItem("Esoteric Melody", 8, true, RandoItemType.Ability, 0xDE, 10),
            new RandomizableItem("Disenchant", 8, true, RandoItemType.Ability, 0xE0, 10),
            new RandomizableItem("Perfect Pitch", 8, true, RandoItemType.Ability, 0xE2, 10),
            new RandomizableItem("Matador's Song", 8, true, RandoItemType.Ability, 0xE4, 10),

            // Black Mage
            new RandomizableItem("Fira", 9, true, RandoItemType.Ability, 0xF2, 40),
            new RandomizableItem("Blizzara", 9, true, RandoItemType.Ability, 0xF4, 40),
            new RandomizableItem("Thundara", 9, true, RandoItemType.Ability, 0xF6, 40),
            new RandomizableItem("Watera", 9, true, RandoItemType.Ability, 0xF8, 40),
            new RandomizableItem("Firaga", 9, true, RandoItemType.Ability, 0xFA, 100),
            new RandomizableItem("Blizzaga", 9, true, RandoItemType.Ability, 0xFC, 100),
            new RandomizableItem("Thundaga", 9, true, RandoItemType.Ability, 0xFE, 100),
            new RandomizableItem("Waterga", 9, true, RandoItemType.Ability, 0x100, 100),
            new RandomizableItem("Focus", 9, true, RandoItemType.Ability, 0xE6, 10),
            new RandomizableItem("MP Absorb", 9, true, RandoItemType.Ability, 0xE8, 10),
            new RandomizableItem("Black Magic Lv2", 9, true, RandoItemType.Ability, 0x480, 40),
            new RandomizableItem("Black Magic Lv3", 9, true, RandoItemType.Ability, 0x482, 60),

            // White Mage
            new RandomizableItem("Vigor", 10, true, RandoItemType.Ability, 0x104, 20),
            new RandomizableItem("Cure", 10, true, RandoItemType.Ability, 0x106, 20),
            new RandomizableItem("Cura", 10, true, RandoItemType.Ability, 0x108, 40),
            new RandomizableItem("Curaga", 10, true, RandoItemType.Ability, 0x10A, 80),
            new RandomizableItem("Regen", 10, true, RandoItemType.Ability, 0x10C, 80),
            new RandomizableItem("Esuna", 10, true, RandoItemType.Ability, 0x10E, 30),
            new RandomizableItem("Dispel", 10, true, RandoItemType.Ability, 0x110, 80),
            new RandomizableItem("Life", 10, true, RandoItemType.Ability, 0x112, 30),
            new RandomizableItem("Full-Life", 10, true, RandoItemType.Ability, 0x114, 160),
            new RandomizableItem("Shell", 10, true, RandoItemType.Ability, 0x116, 30),
            new RandomizableItem("Protect", 10, true, RandoItemType.Ability, 0x118, 30),
            new RandomizableItem("Reflect", 10, true, RandoItemType.Ability, 0x11A, 30),
            new RandomizableItem("Full-Cure", 10, true, RandoItemType.Ability, 0x11C, 80),
            new RandomizableItem("White Magic Lv2", 10, true, RandoItemType.Ability, 0x484, 40),
            new RandomizableItem("White Magic Lv3", 10, true, RandoItemType.Ability, 0x486, 60),

            // Thief
            new RandomizableItem("Pilfer Gil", 11, true, RandoItemType.Ability, 0x120, 30),
            new RandomizableItem("Borrowed Time", 11, true, RandoItemType.Ability, 0x122, 100),
            new RandomizableItem("Pilfer HP", 11, true, RandoItemType.Ability, 0x124, 60),
            new RandomizableItem("Pilfer MP", 11, true, RandoItemType.Ability, 0x126, 60),
            new RandomizableItem("Sticky Fingers", 11, true, RandoItemType.Ability, 0x128, 120),
            new RandomizableItem("Master Thief", 11, true, RandoItemType.Ability, 0x12A, 140),
            new RandomizableItem("Soul Swipe", 11, true, RandoItemType.Ability, 0x12C, 160),
            new RandomizableItem("Steal Will", 11, true, RandoItemType.Ability, 0x12E, 160),
            new RandomizableItem("Flee", 11, true, RandoItemType.Ability, 0x130, 10),
            new RandomizableItem("Item Hunter", 11, true, RandoItemType.Ability, 0x464, 60),
            new RandomizableItem("First Strike", 11, true, RandoItemType.Ability, 0x440, 40),
            new RandomizableItem("Initiative", 11, true, RandoItemType.Ability, 0x442, 60),
            new RandomizableItem("Slowproof", 11, true, RandoItemType.Ability, 0x4FE, 20),
            new RandomizableItem("Stoneproof", 11, true, RandoItemType.Ability, 0x502, 40),

            // Trainer
            new RandomizableItem("Kogoro Freeze", 12, true, RandoItemType.Ability, 0x134, 40),
            new RandomizableItem("Kogoro Shock", 12, true, RandoItemType.Ability, 0x136, 40),
            new RandomizableItem("Kogoro Deluge", 12, true, RandoItemType.Ability, 0x138, 40),
            new RandomizableItem("Kogoro Strike", 12, true, RandoItemType.Ability, 0x13A, 80),
            new RandomizableItem("Doom Kogoro", 12, true, RandoItemType.Ability, 0x13C, 80),
            new RandomizableItem("Kogoro Cure", 12, true, RandoItemType.Ability, 0x13E, 30),
            new RandomizableItem("Kogoro Remedy", 12, true, RandoItemType.Ability, 0x140, 40),
            new RandomizableItem("Pound!", 12, true, RandoItemType.Ability, 0x144, 100),
            new RandomizableItem("Half MP Cost", 12, true, RandoItemType.Ability, 0x478, 200),
            new RandomizableItem("HP Stroll", 12, true, RandoItemType.Ability, 0x468, 20),
            new RandomizableItem("MP Stroll", 12, true, RandoItemType.Ability, 0x46A, 20),
            new RandomizableItem("Kogoro Lv2", 12, true, RandoItemType.Ability, 0x488, 80),
            new RandomizableItem("Kogoro Lv3", 12, true, RandoItemType.Ability, 0x48A, 100),

            // Lady Luck
            new RandomizableItem("Bribe", 13, true, RandoItemType.Ability, 0x180, 40),
            new RandomizableItem("Two Dice", 13, true, RandoItemType.Ability, 0x176, 20),
            new RandomizableItem("Four Dice", 13, true, RandoItemType.Ability, 0x178, 100),
            new RandomizableItem("Magic Reels", 13, true, RandoItemType.Ability, 0x170, 70),
            new RandomizableItem("Item Reels", 13, true, RandoItemType.Ability, 0x172, 80),
            new RandomizableItem("Random Reels", 13, true, RandoItemType.Ability, 0x174, 120),
            new RandomizableItem("Luck", 13, true, RandoItemType.Ability, 0x17A, 30),
            new RandomizableItem("Felicity", 13, true, RandoItemType.Ability, 0x17C, 40),
            new RandomizableItem("Tantalize", 13, true, RandoItemType.Ability, 0x17E, 60),
            new RandomizableItem("Critical", 13, true, RandoItemType.Ability, 0x520, 160),
            new RandomizableItem("Double EXP", 13, true, RandoItemType.Ability, 0x462, 80),
            new RandomizableItem("SOS Spellspring", 13, true, RandoItemType.Ability, 0x532, 30),
            new RandomizableItem("Gillionaire", 13, true, RandoItemType.Ability, 0x45E, 100),
            new RandomizableItem("Double Items", 13, true, RandoItemType.Ability, 0x460, 100),

            // Mascot
            new RandomizableItem("Moogle Jolt", 14, true, RandoItemType.Ability, 0x192, 40),
            new RandomizableItem("Moogle Curaja", 14, true, RandoItemType.Ability, 0x18A, 40),
            new RandomizableItem("Moogle Regenja", 14, true, RandoItemType.Ability, 0x18C, 40),
            new RandomizableItem("Moogle Wallja", 14, true, RandoItemType.Ability, 0x18E, 40),
            new RandomizableItem("Moogle Lifeja", 14, true, RandoItemType.Ability, 0x190, 40),
            new RandomizableItem("Moogle Beam", 14, true, RandoItemType.Ability, 0x194, 80),
            new RandomizableItem("Ribbon", 14, true, RandoItemType.Ability, 0x50E, 999),
            new RandomizableItem("Auto Shell", 14, true, RandoItemType.Ability, 0x514, 80),
            new RandomizableItem("Auto Protect", 14, true, RandoItemType.Ability, 0x516, 80),
            new RandomizableItem("Swordplay", 14, true, RandoItemType.Ability, -33, 80),
            new RandomizableItem("Arcana", 14, true, RandoItemType.Ability, -29, 80),

            // Psychic
             new RandomizableItem("Maser Eye", 28, true, RandoItemType.Ability, 0x370, 30),
             new RandomizableItem("Telekinesis", 28, true, RandoItemType.Ability, 0x36E, 30),
             new RandomizableItem("Brainstorm", 28, true, RandoItemType.Ability, 0x372, 30),
             new RandomizableItem("Express", 28, true, RandoItemType.Ability, 0x376, 40),
             new RandomizableItem("Teleport", 28, true, RandoItemType.Ability, 0x37C, 30),
             new RandomizableItem("Time Trip", 28, true, RandoItemType.Ability, 0x374, 100),
             new RandomizableItem("Magic Guard", 28, true, RandoItemType.Ability, 0x378, 80),
             new RandomizableItem("Physics Guard", 28, true, RandoItemType.Ability, 0x37A, 80),
             new RandomizableItem("Excellence", 28, true, RandoItemType.Ability, 0x37E, 120),
             new RandomizableItem("Fire Eater", 28, true, RandoItemType.Ability, 0x49A, 40),
             new RandomizableItem("Ice Eater", 28, true, RandoItemType.Ability, 0x4A2, 40),
             new RandomizableItem("Lightning Eater", 28, true, RandoItemType.Ability, 0x4AB, 40),
             new RandomizableItem("Water Eater", 28, true, RandoItemType.Ability, 0x4B2, 40),
             new RandomizableItem("Gravity Eater", 28, true, RandoItemType.Ability, 0x3BA, 60),

             // Festivalist
             new RandomizableItem("Twinkler", 29, true, RandoItemType.Ability, 0x394, 40),
             new RandomizableItem("Spinner", 29, true, RandoItemType.Ability, 0x388, 40),
             new RandomizableItem("Popper", 29, true, RandoItemType.Ability, 0x38E, 40),
             new RandomizableItem("Fountain", 29, true, RandoItemType.Ability, 0x39A, 40),
             new RandomizableItem("Ice Sandals", 29, true, RandoItemType.Ability, 0x3A2, 30),
             new RandomizableItem("Water Sandals", 29, true, RandoItemType.Ability, 0x3A6, 30),
             new RandomizableItem("Flare Sandals", 29, true, RandoItemType.Ability, 0x3A8, 60),
             new RandomizableItem("Ultima Sandals", 29, true, RandoItemType.Ability, 0x3AA, 160),
             new RandomizableItem("Piercing Magic", 29, true, RandoItemType.Ability, 0x466, 30),
             new RandomizableItem("Silenceproof", 29, true, RandoItemType.Ability, 0xDC, 10),
             new RandomizableItem("Pointlessproof", 29, true, RandoItemType.Ability, 0xDE, 10),
             new RandomizableItem("SOS Regen", 29, true, RandoItemType.Ability, 0x52E, 30),
             new RandomizableItem("SOS Wall", 29, true, RandoItemType.Ability, 0x576, 30),

             // Floral Fallal
             /*new RandomizableItem("Libra", 15, true, RandoItemType.Ability, 0x1CA, 4),
             new RandomizableItem("Barrier", 15, true, RandoItemType.Ability, 0x1C8, 20),
             new RandomizableItem("Shield", 15, true, RandoItemType.Ability, 0x1C6, 20),
             new RandomizableItem("Flare Whirl", 15, true, RandoItemType.Ability, 0x1CC, 24),
             new RandomizableItem("Great Whirl", 15, true, RandoItemType.Ability, 0x1D0, 30),
             new RandomizableItem("All-Life", 15, true, RandoItemType.Ability, 0x1CE, 8),
             new RandomizableItem("Double HP", 15, true, RandoItemType.Ability, 0x524, 20),
             new RandomizableItem("Triple HP", 15, true, RandoItemType.Ability, 0x526, 30),
             new RandomizableItem("Break HP Limit", 15, true, RandoItemType.Ability, 0x456, 20),
             new RandomizableItem("Break Damage Limit", 15, true, RandoItemType.Ability, 0x45A, 20),

             // Right Pistil
             new RandomizableItem("White Honey", 16, true, RandoItemType.Ability, 0x15B4, 4),
             new RandomizableItem("Floral Rush", 16, true, RandoItemType.Ability, 0x15BC, 20),
             new RandomizableItem("Fallal Bomb", 16, true, RandoItemType.Ability, 0x15C0, 10),
             new RandomizableItem("Floral Magisol", 16, true, RandoItemType.Ability, 0x15C2, 10),
             new RandomizableItem("Fallal Magisol", 16, true, RandoItemType.Ability, 0x15C4, 10),
             new RandomizableItem("Right Stigma", 16, true, RandoItemType.Ability, 0x15C6, 20),
             new RandomizableItem("Double HP", 16, true, RandoItemType.Ability, 0x1904, 20),
             new RandomizableItem("Triple HP", 16, true, RandoItemType.Ability, 0x1906, 30),
             new RandomizableItem("Break HP Limit", 16, true, RandoItemType.Ability, 0x1836, 20),
             new RandomizableItem("Break Damage Limit", 16, true, RandoItemType.Ability, 0x183A, 20),*/

        };
    }
}
